### ISSUE TITLE
Sending EOF (e.g. pressing Ctrl-D) crashes opsdroid

### ISSUE THREAD

**Issue by gergelypolonkai** [opsdroid/connector-shell#7]
When i press Ctrl-D (on Linux) in the shell connector, the bot outputs the prompt numerous times (without a newline), then crashes.

**Comment by jacobtomlinson** [comment]
Thanks for raising this. There is some work in the pipeline to merge this library into the core of opsdroid. That will provide a good opportinuty to review this kind of stuff.

In the mean time I recommend using the websocket connector and the [opsdroid desktop](https://github.com/opsdroid/opsdroid-desktop) client for testing.
